export enum EnvKeyConstant {
    PORT="PORT",
    JWT_ACCESS_TOKEN_EXPIRATION_TIME="JWT_ACCESS_TOKEN_EXPIRATION_TIME",
    JWT_REFRESH_TOKEN_EXPIRATION_TIME="JWT_REFRESH_TOKEN_EXPIRATION_TIME",
    JWT_VERIFY_TOKEN_EXPIRATION_TIME="JWT_VERIFY_TOKEN_EXPIRATION_TIME",
    JWT_REQUEST_TOKEN_EXPIRATION_TIME="JWT_REQUEST_TOKEN_EXPIRATION_TIME",
    SECRET_KEY="SECRET_KEY",
    REFRESH_TOKEN_KEY="REFRESH_TOKEN_KEY",
    POSTGRES_HOST="POSTGRES_HOST",
    POSTGRES_PORT="POSTGRES_PORT",
    POSTGRES_USER="POSTGRES_USER",
    POSTGRES_PASSWORD="POSTGRES_PASSWORD",
    POSTGRES_DB="POSTGRES_DB"
}